# Generated by Django 3.2 on 2023-02-22 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(error_messages={'validators': 'Оценка должна быть от 1 до 10'}, help_text='Введите оценку от 1 до 10', validators=[django.core.validators.MinValueValidator(1, 'Значение не может быть меньше 1'), django.core.validators.MaxValueValidator(10, 'Значение не может быть больше 10')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(db_index=True, related_name='titles', to='reviews.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, error_messages={'validators': 'Введите корректный год издания'}, help_text='Введите год издания', validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2023)], verbose_name='Год издания'),
        ),
    ]
