# Generated by Django 3.2 on 2023-02-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230222_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=36, verbose_name='Код подтверждения'),
        ),
    ]
